### ISSUE TITLE
New install of UNMS doesn't correctly create docker-compose.yml

### ISSUE THREAD

**Issue by marcusmyers** [Ubiquiti-App/UNMS#126]
When doing an new install of UNMS the install script fails at `stop_docker_containers` function with an output of:

```bash
ERROR: yaml.parser.ParserError: while parsing a block collection
  in "./docker-compose.yml", line 136, column 7
expected <block end>, but found '<scalar>'
  in "./docker-compose.yml", line 137, column 23
Failed to stop docker containers
```

The generated `docker-compose.yml` has some errors. See below:

```yaml
unms:
    container_name: unms
    image: ubnt/unms:0.11.3
    restart: always
    depends_on:
      - fluentd
      - redis
      - postgres
    networks:
      - internal
      - public
    volumes:
      - /home/unms/data:/home/app/unms/data
    logging:
      driver: fluentd
      options:
        tag: "unms"
        fluentd-async-connect: "true"
    environment:
      - UNMS_USER_ID=5501
      - DEMO=false
      - NODE_ENV=production
      - HTTP_PORT=8081
      - WS_PORT=8082
      - SSL_CERT=
      - PUBLIC_HTTPS_PORT=if ! rm -rf "${temp}"; then
      - PUBLIC_WS_PORT=
      - HOST_TAG=
      - BRANCH=master
      - http_proxy=
      - HTTP_PROXY=
      - https_proxy=
      - HTTPS_PROXY=
      - no_proxy=
      - NO_PROXY=
      - SECURE_LINK_SECRET=ciUNcMi9vUW56A2LBXPLme1evDkuYNkHQjOJmXx7DbxITEPhM4J3BCtuZUd33Hw2DRRaOx28j3ISqOoSq6iPbzBdnevSghRDoMC1

  nginx:
    image: ubnt/unms-nginx:0.11.3
    container_name: unms-nginx
    restart: always
    ports:
      - "cd ~:cd ~"
      - "if ! rm -rf "${temp}"; then:if ! rm -rf "${temp}"; then"
    networks:
      - public
    volumes:
      - /home/unms/data/cert:/cert
      - /home/unms/data/firmwares:/www/firmwares
    depends_on:
      - unms
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: "nginx"
        fluentd-async-connect: "true"
    environment:
      - NGINX_UID=5501
      - SSL_CERT=
      - SSL_CERT_KEY=
      - SSL_CERT_CA=
      - HTTP_PORT=cd ~
      - HTTPS_PORT=if ! rm -rf "${temp}"; then
      - WS_PORT=
      - UNMS_HTTP_PORT=8081
      - UNMS_WS_PORT=8082
      - PUBLIC_HTTPS_PORT=if ! rm -rf "${temp}"; then
      - SECURE_LINK_SECRET=ciUNcMi9vUW56A2LBXPLme1evDkuYNkHQjOJmXx7DbxITEPhM4J3BCtuZUd33Hw2DRRaOx28j3ISqOoSq6iPbzBdnevSghRDoMC1
```

Notice the port port issues in the nginx and unms services.
