### ISSUE TITLE
Deploying with Traefik as Reverse Proxy

### ISSUE THREAD

**Issue by seffyroff** [Ubiquiti-App/UNMS#148]
Hi folks!

With the current install method I'm having a really hard time integrating it with my existing infrastructure - Docker Swarm with Traefik reverse proxying. 

Moving ports around and setting up networks has sent me cross-eyed here, and I am tired, frustrated and ready to give up.  Has anyone any advice for setting this up with my kind of setup please?

I have noticed a few unofficial containers here that combine your distribution into a single image - that's not what I want, I'd like to have separate containers per service, and Ideally be able to deploy across the nodes on my swarm so they aren't all stuck together on the same host.

**Comment by seffyroff** [comment]
In an attempt to see what was wrong, I rewrote the docker-compose.yml that the install script generates, and commented out any settings that don't work in a swarm environment, where possible replacing with swarm versions (like network alias instead of container_name).  I also removed fluentd so I can do my own logging.  I also commented out cap_add: NET_ADMIN on the unms container (why does it need this?).  I also chown'd the contents of the unms/app and unms/data directories to the user that generally runs and admins Docker on the swarm, and set the UID envs on several containers to that user's ID.

Here's what it looks like.   No, it doesn't work.  Internal Server Error is what I see when I try to hit the endpoint on my LB.  I welcome any comments or suggestions here.

```
version: '3.5'

networks:
  public:
    external: true
    name: consul_backend  
  internal:
    internal: true
    

services:
  # fluentd:
  #   container_name: unms-fluentd
  #   image: ubnt/unms-fluentd:0.12.2
  #   deploy:
  #     restart_policy:
  #       condition: any
  #   restart: always
  #   networks:
  #     - public
  #   ports:
  #     - "127.0.0.1:24224:24224"
  #   volumes:
  #     - /var/data/unms/app/conf/fluent.conf:/etc/fluent/fluent.conf
  #     - /var/data/unms/data/logs:/fluentd/log
  #   environment:
  #     - FLUENTD_UID=1001

  redis:
    # container_name: unms-redis
    image: redis:3.2.8-alpine
    user: "1000"
    deploy:
      restart_policy:
        condition: any
    # depends_on:
    #   - fluentd
    networks:
      internal:
        aliases:
          - unms-redis
    volumes:
      - /var/data/unms/data/redis:/data/db
    # logging:
    #   driver: fluentd
    #   options:
    #     tag: "redis"
    #     fluentd-async-connect: "true"
    command: "redis-server --appendonly yes --dir /data/db/"

  # we still run postgres as root with stepdown to uid 70 until this issue is fixed
  # https://github.com/docker-library/postgres/issues/264
  # and until it's not required to expose host's /etc/passwd to the container
  # https://hub.docker.com/_/postgres/ (see "Arbitrary --user Notes")
  postgres:
    # container_name: unms-postgres
    image: postgres:9.6.1-alpine
    deploy:
      restart_policy:
        condition: any
    # depends_on:
    #   - fluentd
    networks:
      internal:
        aliases:
          - unms-postgres
    volumes:
      - /var/data/unms/data/postgres:/var/lib/postgresql/data/pgdata
    # logging:
    #   driver: fluentd
    #   options:
    #     tag: "postgres"
    #     fluentd-async-connect: "true"
    environment:
      - POSTGRES_DB=unms
      - PGDATA=/var/lib/postgresql/data/pgdata

  rabbitmq:
    # container_name: unms-rabbitmq
    image: rabbitmq:3.7.4-alpine
    deploy:
      restart_policy:
        condition: any
    # depends_on:
    #   - fluentd
    networks:
      internal:
        aliases:
          - unms-rabbitmq
    # depends_on:
    #   - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     tag: "rabbitmq"
    #     fluentd-async-connect: "true"

  unms:
    # container_name: unms
    image: ubnt/unms:0.12.2
    deploy:
      restart_policy:
        condition: any
    # depends_on:
    #   - fluentd
    #   - redis
    #   - postgres
    networks:
      internal:
        aliases:
          - unms
      public:
    volumes:
      - /var/data/unms/data:/home/app/unms/data
    # logging:
    #   driver: fluentd
    #   options:
    #     tag: "unms"
    #     fluentd-async-connect: "true"
    environment:
      - UNMS_USER_ID=1000
      - DEMO=false
      - NODE_ENV=production
      - HTTP_PORT=8081
      - WS_PORT=8082
      - WS_SHELL_PORT=8083
      - UNMS_WS_API_PORT=8084
      - SSL_CERT=
      - PUBLIC_HTTPS_PORT=443
      - PUBLIC_WS_PORT=443
      - HOST_TAG=
      - BRANCH=master
      - http_proxy=
      - HTTP_PROXY=
      - https_proxy=
      - HTTPS_PROXY=
      - no_proxy=
      - NO_PROXY=
      - SECURE_LINK_SECRET=aopdZMprJQg17lY5S9HK0tV09yjVAaQ24MAUL1rDr2Q2zpHV0cmKhJ4lhTa8Iu88uIoV5SGRmx7lNV2cXn9m2GLYrtRzFFZaR5Y1
    # cap_add:
    #   - NET_ADMIN

  nginx:
    image: ubnt/unms-nginx:0.12.2
    # container_name: unms-nginx
    deploy:
      restart_policy:
        condition: any
      labels:
        - traefik.enable=true
        - traefik.frontend.rule=Host:unms.myhost.org
        - traefik.docker.network=consul_backend
        - traefik.port=443
        - traefik.protocol=https
    # ports:
    #   - "8128:8128"
    #   - "8256:8256"
      # expose:
      #   - "80"
      #   - "443"
    networks:
      public:
        aliases:
          - unms-nginx
      internal:
        aliases:
          - unms-nginx
    volumes:
      - /var/data/unms/data/cert:/cert
      
      - /var/data/unms/data/firmwares:/www/firmwares
    # depends_on:
    #   - unms
    #   - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     tag: "nginx"
    #     fluentd-async-connect: "true"
    environment:
      - NGINX_UID=1000
      - SSL_CERT=
      - SSL_CERT_KEY=
      - SSL_CERT_CA=
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - WS_PORT=
      - UNMS_HTTP_PORT=8081
      - UNMS_WS_PORT=8082
      - UNMS_WS_SHELL_PORT=8083
      - UNMS_WS_API_PORT=8084
      - PUBLIC_HTTPS_PORT=443
      - SECURE_LINK_SECRET=xxxx
```
